"""initial schema

Revision ID: 6d4239643387
Revises:
Create Date: 2026-09-09 00:28:39.319258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d4239643387"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("designation", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=128), nullable=False),
        sa.Column("cost_centre", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("reporting_manager_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "Employee",
                "Reporting Manager",
                "Head of Department",
                "Head of Division",
                "Finance",
                "MD",
                name="employee_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reporting_manager_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employee_code"),
    )
    op.create_table(
        "travel_requests",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("travel_request_id", sa.String(length=32), nullable=False),
        sa.Column("employee_id", sa.BigInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column(
            "travel_category",
            sa.Enum(
                "Domestic - Tier 1",
                "Domestic - Tier 2",
                "Domestic - Tier 3",
                "International",
                name="travel_category",
                native_enum=False,
            ),
            server_default="Domestic - Tier 1",
            nullable=False,
        ),
        sa.Column(
            "travel_mode",
            sa.Enum(
                "Flight", "Rail", "Road", "Other", name="travel_mode", native_enum=False
            ),
            server_default="Flight",
            nullable=False,
        ),
        sa.Column(
            "currency", sa.String(length=8), server_default="INR", nullable=False
        ),
        sa.Column(
            "estimated_heads",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "estimated_cost",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "advance_requested",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "advance_disbursed",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_approval",
                "approved",
                "in_settlement",
                "closed",
                name="travel_request_status",
                native_enum=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("travel_request_id"),
    )
    op.create_index(
        op.f("ix_travel_requests_employee_id"),
        "travel_requests",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "travel_request_approvals",
        sa.Column("travel_request_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column(
            "role_required",
            sa.Enum(
                "Employee",
                "Reporting Manager",
                "Head of Department",
                "Head of Division",
                "Finance",
                "MD",
                name="employee_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("approver_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "approved",
                "returned",
                "rejected",
                "skipped",
                name="approval_decision",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"], ["travel_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "travel_request_id", "level", name="uq_travel_request_approvals_level"
        ),
    )
    op.create_index(
        op.f("ix_travel_request_approvals_approver_id"),
        "travel_request_approvals",
        ["approver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_travel_request_approvals_travel_request_id"),
        "travel_request_approvals",
        ["travel_request_id"],
        unique=False,
    )
    op.create_table(
        "travel_settlements",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("travel_request_id", sa.BigInteger(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "returned",
                "in_approval",
                "finance_review",
                "queued_for_payment",
                "paid",
                "recoverable",
                name="settlement_status",
                native_enum=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "total_employee_paid",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "total_company_paid",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "disallowed_total",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "net_reimbursable",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "advance_applied",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "amount_payable",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "amount_recoverable",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["travel_request_id"],
            ["travel_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("travel_request_id"),
    )
    op.create_index(
        op.f("ix_travel_settlements_status"),
        "travel_settlements",
        ["status"],
        unique=False,
    )
    op.create_table(
        "travel_expenses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("travel_settlement_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "lodging",
                "transport",
                "other",
                name="expense_section",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expense_date", sa.Date(), nullable=True),
        sa.Column(
            "paid_by",
            sa.Enum("Employee", "Company", name="paid_by", native_enum=False),
            server_default="Employee",
            nullable=False,
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("proof_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "disallowed_amount",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("disallow_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["travel_settlement_id"], ["travel_settlements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_travel_expenses_travel_settlement_id"),
        "travel_expenses",
        ["travel_settlement_id"],
        unique=False,
    )
    op.create_table(
        "travel_settlement_approvals",
        sa.Column("travel_settlement_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column(
            "role_required",
            sa.Enum(
                "Employee",
                "Reporting Manager",
                "Head of Department",
                "Head of Division",
                "Finance",
                "MD",
                name="employee_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("approver_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "pending",
                "approved",
                "returned",
                "rejected",
                "skipped",
                name="approval_decision",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["travel_settlement_id"], ["travel_settlements.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "travel_settlement_id", "level", name="uq_travel_settlement_approvals_level"
        ),
    )
    op.create_index(
        op.f("ix_travel_settlement_approvals_approver_id"),
        "travel_settlement_approvals",
        ["approver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_travel_settlement_approvals_travel_settlement_id"),
        "travel_settlement_approvals",
        ["travel_settlement_id"],
        unique=False,
    )
    op.create_table(
        "travel_expense_lodging",
        sa.Column("travel_expense_id", sa.BigInteger(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("hotel_name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["travel_expense_id"], ["travel_expenses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("travel_expense_id"),
    )
    op.create_table(
        "travel_expense_other",
        sa.Column("travel_expense_id", sa.BigInteger(), nullable=False),
        sa.Column("head", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["travel_expense_id"], ["travel_expenses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("travel_expense_id"),
    )
    op.create_table(
        "travel_expense_transport",
        sa.Column("travel_expense_id", sa.BigInteger(), nullable=False),
        sa.Column("expense_time", sa.Time(), nullable=True),
        sa.Column("from_location", sa.String(length=255), nullable=False),
        sa.Column("to_location", sa.String(length=255), nullable=False),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["travel_expense_id"], ["travel_expenses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("travel_expense_id"),
    )
    # ### end Alembic commands ###

    # Seed employees from docs/employee_master.csv
    # id = numeric part of NX-####; reporting_manager_id → employees.id
    employees = sa.table(
        "employees",
        sa.column("id", sa.BigInteger),
        sa.column("employee_code", sa.String),
        sa.column("name", sa.String),
        sa.column("email", sa.String),
        sa.column("designation", sa.String),
        sa.column("department", sa.String),
        sa.column("cost_centre", sa.String),
        sa.column("city", sa.String),
        sa.column("reporting_manager_id", sa.BigInteger),
        sa.column("role", sa.String),
    )
    op.bulk_insert(
        employees,
        [
            {
                "id": 1000,
                "employee_code": "NX-1000",
                "name": "Nandita Shah",
                "email": "nandita.shah@nortexindustries.com",
                "designation": "Managing Director",
                "department": "Corporate",
                "cost_centre": "CE001",
                "city": "Mumbai",
                "reporting_manager_id": None,
                "role": "MD",
            },
            {
                "id": 1002,
                "employee_code": "NX-1002",
                "name": "Arvind Rao",
                "email": "arvind.rao@nortexindustries.com",
                "designation": "Head of Division - Commercial",
                "department": "Commercial",
                "cost_centre": "CE001",
                "city": "Mumbai",
                "reporting_manager_id": 1000,
                "role": "Head of Division",
            },
            {
                "id": 1108,
                "employee_code": "NX-1108",
                "name": "Meera Krishnan",
                "email": "meera.krishnan@nortexindustries.com",
                "designation": "Head of Department - Sales",
                "department": "Sales",
                "cost_centre": "CE100",
                "city": "Mumbai",
                "reporting_manager_id": 1002,
                "role": "Head of Department",
            },
            {
                "id": 2210,
                "employee_code": "NX-2210",
                "name": "Suresh Iyer",
                "email": "suresh.iyer@nortexindustries.com",
                "designation": "Deputy General Manager",
                "department": "Sales",
                "cost_centre": "CE110",
                "city": "Pune",
                "reporting_manager_id": 1108,
                "role": "Reporting Manager",
            },
            {
                "id": 3300,
                "employee_code": "NX-3300",
                "name": "Kavitha Balan",
                "email": "kavitha.balan@nortexindustries.com",
                "designation": "Controller",
                "department": "Finance",
                "cost_centre": "CE900",
                "city": "Pune",
                "reporting_manager_id": 1002,
                "role": "Finance",
            },
            {
                "id": 3305,
                "employee_code": "NX-3305",
                "name": "Ravi Menon",
                "email": "ravi.menon@nortexindustries.com",
                "designation": "Manager - Finance Shared Services",
                "department": "Finance",
                "cost_centre": "CE900",
                "city": "Pune",
                "reporting_manager_id": 3300,
                "role": "Finance",
            },
            {
                "id": 4471,
                "employee_code": "NX-4471",
                "name": "Chaitanya Reddy",
                "email": "chaitanya.reddy@nortexindustries.com",
                "designation": "Manager - Key Accounts",
                "department": "Sales",
                "cost_centre": "CE110",
                "city": "Pune",
                "reporting_manager_id": 2210,
                "role": "Employee",
            },
            {
                "id": 4490,
                "employee_code": "NX-4490",
                "name": "Imran Qureshi",
                "email": "imran.qureshi@nortexindustries.com",
                "designation": "Executive - Sales",
                "department": "Sales",
                "cost_centre": "CE110",
                "city": "Pune",
                "reporting_manager_id": 2210,
                "role": "Employee",
            },
            {
                "id": 5182,
                "employee_code": "NX-5182",
                "name": "Deepa Nair",
                "email": "deepa.nair@nortexindustries.com",
                "designation": "Manager - Presales",
                "department": "Sales",
                "cost_centre": "CE110",
                "city": "Chennai",
                "reporting_manager_id": 2210,
                "role": "Employee",
            },
        ],
    )
    # Keep identity sequence ahead of the highest explicit id
    op.execute(
        sa.text(
            "SELECT setval(pg_get_serial_sequence('employees', 'id'), "
            "(SELECT MAX(id) FROM employees))"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_expense_transport")
    op.drop_table("travel_expense_other")
    op.drop_table("travel_expense_lodging")
    op.drop_index(
        op.f("ix_travel_settlement_approvals_travel_settlement_id"),
        table_name="travel_settlement_approvals",
    )
    op.drop_index(
        op.f("ix_travel_settlement_approvals_approver_id"),
        table_name="travel_settlement_approvals",
    )
    op.drop_table("travel_settlement_approvals")
    op.drop_index(
        op.f("ix_travel_expenses_travel_settlement_id"), table_name="travel_expenses"
    )
    op.drop_table("travel_expenses")
    op.drop_index(op.f("ix_travel_settlements_status"), table_name="travel_settlements")
    op.drop_table("travel_settlements")
    op.drop_index(
        op.f("ix_travel_request_approvals_travel_request_id"),
        table_name="travel_request_approvals",
    )
    op.drop_index(
        op.f("ix_travel_request_approvals_approver_id"),
        table_name="travel_request_approvals",
    )
    op.drop_table("travel_request_approvals")
    op.drop_index(op.f("ix_travel_requests_employee_id"), table_name="travel_requests")
    op.drop_table("travel_requests")
    op.drop_table("employees")
    # ### end Alembic commands ###
